In [20]:
# Broad Casting & Numpy - Column_stack()

In [3]:
import numpy as np

In [9]:
# Broad Casting
nums = np.array([10, 20, 30, 40])

print(nums)

[10 20 30 40]


In [13]:
# 요소 각각에 적용 = Broad Casting
nums2 = nums * 2

print(nums2)

[20 40 60 80]


In [16]:
nums3 = nums -5

print(nums3)

[ 5 15 25 35]


In [ ]:
# column_stack(Tuple(..., ...)
# Python 내장 함수인 zip()과 유사

In [19]:
data = np.column_stack(([10, 20, 30], [1, 2, 3,], [100, 200, 300]))

print(data)

[[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]]
